config/routes.rb
Rails.application.routes.draw do
  

  get 'pessoas/update_cidades', as: 'update_cidades'
  get 'pessoas/:id/update_cidades' => 'questoes#update_cidades'

  resources :pessoas

  root 'pessoas#index'

end

app/models/cidade.rb
class Cidade < ActiveRecord::Base
  belongs_to :estado
end

app/models/estado.rb
class Estado < ActiveRecord::Base
	has_many :cidades
end

app/models/pessoa.rb
class Pessoa < ActiveRecord::Base
  belongs_to :cidade
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/pessoas_controller.rb
class PessoasController < ApplicationController
  before_action :set_pessoa, only: [:show, :edit, :update, :destroy]

  # GET /pessoas
  # GET /pessoas.json
  def index
    @pessoas = Pessoa.all
  end

  # GET /pessoas/1
  # GET /pessoas/1.json
  def show
  end

  # GET /pessoas/new
  def new
    @pessoa = Pessoa.new
    

    @estados = Estado.all
    @cidades = Cidade.where("estado_id = ?", Estado.first.id)
  end

  # GET /pessoas/1/edit
  def edit
  end

  # POST /pessoas
  # POST /pessoas.json
  def create
    @pessoa = Pessoa.new(pessoa_params)

    respond_to do |format|
      if @pessoa.save
        format.html { redirect_to @pessoa, notice: 'Pessoa was successfully created.' }
        format.json { render :show, status: :created, location: @pessoa }
      else
        format.html { render :new }
        format.json { render json: @pessoa.errors, status: :unprocessable_entity }
      end
    end
  end

  def update_cidades

    @cidades = Cidade.where("estado_id = ?", params[:estado_id])
    respond_to do |format|
      format.js
    end
  end

  # PATCH/PUT /pessoas/1
  # PATCH/PUT /pessoas/1.json
  def update
    respond_to do |format|
      if @pessoa.update(pessoa_params)
        format.html { redirect_to @pessoa, notice: 'Pessoa was successfully updated.' }
        format.json { render :show, status: :ok, location: @pessoa }
      else
        format.html { render :edit }
        format.json { render json: @pessoa.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /pessoas/1
  # DELETE /pessoas/1.json
  def destroy
    @pessoa.destroy
    respond_to do |format|
      format.html { redirect_to pessoas_url, notice: 'Pessoa was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_pessoa
      @pessoa = Pessoa.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def pessoa_params
      params.require(:pessoa).permit(:nome, :cidade_id)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/pessoas_helper.rb
module PessoasHelper
end

app/views/cidades/_cidade.html.erb
<option value="<%= cidade.id %>"><%= cidade.nome %></option>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>ExampleCidadesEstados</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>

app/views/pessoas/_form.html.erb
<%= form_for(@pessoa) do |f| %>
  <% if @pessoa.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@pessoa.errors.count, "error") %> prohibited this pessoa from being saved:</h2>

      <ul>
      <% @pessoa.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :nome %><br>
    <%= f.text_field :nome %>
  </div>

  <div class="field">
    <%= label_tag :estado %>
    <%= collection_select(:estado, :id, @estados, :id, :nome, { prompt: "Selecione o estado"}, {id: 'estados_select'})  %>
    
  </div>
  <div class="field">
    <%= f.label :cidade_id %>
    <%= f.select :cidade_id, options_for_select(@cidades.collect { |cidade|
    [cidade.nome.titleize, cidade.id] }, 0), {}, { id: 'cidades_select'} %>    
  </div>
  
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/pessoas/edit.html.erb
<h1>Editing Pessoa</h1>

<%= render 'form' %>

<%= link_to 'Show', @pessoa %> |
<%= link_to 'Back', pessoas_path %>

app/views/pessoas/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Pessoas</h1>

<table>
  <thead>
    <tr>
      <th>Nome</th>
      <th>Estado</th>
      <th>Cidade</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @pessoas.each do |pessoa| %>
      <tr>
        <td><%= pessoa.nome %></td>
        <td><%= pessoa.cidade %></td>
        <td><%= pessoa.cidade.nome %></td>
        <td><%= link_to 'Show', pessoa %></td>
        <td><%= link_to 'Edit', edit_pessoa_path(pessoa) %></td>
        <td><%= link_to 'Destroy', pessoa, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Pessoa', new_pessoa_path %>

app/views/pessoas/new.html.erb
<h1>New Pessoa</h1>

<%= render 'form' %>

<%= link_to 'Back', pessoas_path %>

app/views/pessoas/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Nome:</strong>
  <%= @pessoa.nome %>
</p>
<p>
  <strong>Estado:</strong>
  <%= @pessoa.cidade.estado.nome %>
</p>
<p>
  <strong>Cidade:</strong>
  <%= @pessoa.cidade.nome %>
</p>

<%= link_to 'Edit', edit_pessoa_path(@pessoa) %> |
<%= link_to 'Back', pessoas_path %>